### PR TITLE
Cash flow target amount - copy when ad hoc reruns is enabled - [PLAT-34420]

### PR DESCRIPTION
**Pull request by nc-gibsonj**
Change for cash flow target amount paragraph copy (for ad hoc reruns) to be consistent with the default copy.

image

### CODE REVIEW

**Comment by nc-sjoquistn** [comment]
@nc-gibsonj should the second occurrence also be target > goal?

**Comment by nc-sjoquistn** [comment]
@nc-gibsonj does the adhoc copy only show for an enrolled user?

**Comment by nc-gibsonj** [comment]
Nope it shows if ad hoc reruns is enabled. https://github.com/BLC/nextcapital-design-objects/blob/5864b74bbb866f822a0964c45135122e2cc6272f/src/components/cash-flow/cash-flow-target-amount/CashFlowTargetAmountTable.jsx#L33

**Comment by nc-sjoquistn** [comment]
let's hold off on this change since this wasn't in the copy spreadsheet.

**Comment by nc-gibsonj** [comment]
Updated

**Comment by nc-gibsonj** [comment]
image

**Pull request merged**
